// ─────────────────────────────────────────────────────────────────
// MCP TEE Server — Azure Confidential Container on ACI
//
// Deploys:
//   1. ACI Container Group (sku: Confidential, AMD SEV-SNP)
//   2. Azure Key Vault with mHSM key-release policy
//   3. Managed Identity for the container to call AKV
//   4. Azure Container Registry reference
//
// The CCE security policy (base64) must be generated BEFORE deployment
// using the confcom CLI and passed as a parameter.
//
// Usage:
//   az deployment group create \
//     --resource-group <rg> \
//     --template-file infra/main.bicep \
//     --parameters \
//         acrName=<acr> \
//         imageTag=latest \
//         ccePolicy=<base64-policy>
// ─────────────────────────────────────────────────────────────────

@description('Name of the Azure Container Registry holding the MCP server image')
param acrName string

@description('Image tag to deploy')
param imageTag string = 'latest'

@description('Base64-encoded CCE security policy (generated by az confcom acipolicy gen)')
@secure()
param ccePolicy string

@description('Azure region for all resources')
param location string = resourceGroup().location

@description('Name prefix for all resources')
param namePrefix string = 'mcp-tee'

// ── Variables ───────────────────────────────────────────────────
var containerGroupName = '${namePrefix}-server'
var keyVaultName = '${namePrefix}-kv-${uniqueString(resourceGroup().id)}'
var managedIdentityName = '${namePrefix}-identity'
var imageName = '${acrName}.azurecr.io/mcp-tee-server:${imageTag}'

// ── Managed Identity ────────────────────────────────────────────
resource managedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityName
  location: location
}

// ── Key Vault (for secret storage with key-release policy) ──────
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  properties: {
    sku: {
      family: 'A'
      name: 'premium' // Required for HSM-backed keys and Secure Key Release (SKR) policies
    }
    tenantId: subscription().tenantId
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
    networkAcls: {
      defaultAction: 'Deny'
      bypass: 'AzureServices'
    }
  }
}

// ── Key Vault Secrets ───────────────────────────────────────────
// In production, these are populated by your CI/CD pipeline or
// a separate secure provisioning step. The key-release policy
// ensures they can ONLY be read by attested confidential containers.

resource githubTokenSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'github-token'
  properties: {
    value: '' // Populated externally — never in source control
    contentType: 'text/plain'
  }
}

resource dbConnectionSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'db-connection-string'
  properties: {
    value: '' // Populated externally
    contentType: 'text/plain'
  }
}

resource webhookUrlSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'webhook-url'
  properties: {
    value: '' // Populated externally
    contentType: 'text/plain'
  }
}

// ── RBAC: Grant the managed identity access to Key Vault secrets ─
// Role: Key Vault Secrets User (4633458b-17de-408a-b874-0445c86b69e6)
resource kvRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, managedIdentity.id, '4633458b-17de-408a-b874-0445c86b69e6')
  scope: keyVault
  properties: {
    roleDefinitionId: subscriptionResourceId(
      'Microsoft.Authorization/roleDefinitions',
      '4633458b-17de-408a-b874-0445c86b69e6'
    )
    principalId: managedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// ── ACI Confidential Container Group ────────────────────────────
resource containerGroup 'Microsoft.ContainerInstance/containerGroups@2023-05-01' = {
  name: containerGroupName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentity.id}': {}
    }
  }
  properties: {
    // ─── Confidential Computing SKU ───────────────────────────
    sku: 'Confidential'
    confidentialComputeProperties: {
      ccePolicy: ccePolicy // Hardware-enforced security policy
    }

    osType: 'Linux'
    restartPolicy: 'OnFailure'

    // ─── Container Image ──────────────────────────────────────
    containers: [
      {
        name: 'mcp-server'
        properties: {
          image: imageName
          resources: {
            requests: {
              cpu: 1
              memoryInGB: 2
            }
          }
          // Secrets injected as environment variables by the
          // attestation sidecar AFTER successful attestation.
          // These are placeholders — the sidecar overwrites them.
          environmentVariables: [
            {
              name: 'GITHUB_TOKEN'
              secureValue: '' // Injected by sidecar post-attestation
            }
            {
              name: 'DB_CONNECTION_STRING'
              secureValue: '' // Injected by sidecar post-attestation
            }
            {
              name: 'WEBHOOK_URL'
              secureValue: '' // Injected by sidecar post-attestation
            }
            {
              name: 'AZURE_KEY_VAULT_URL'
              value: keyVault.properties.vaultUri
            }
          ]
          ports: [
            {
              port: 8080
              protocol: 'TCP'
            }
          ]
        }
      }
    ]

    // ─── Network: expose the MCP server port ──────────────────
    ipAddress: {
      type: 'Public'
      ports: [
        {
          port: 8080
          protocol: 'TCP'
        }
      ]
    }

    // ─── Image Registry Credentials ───────────────────────────
    imageRegistryCredentials: [
      {
        server: '${acrName}.azurecr.io'
        identity: managedIdentity.id
      }
    ]
  }
}

// ── Outputs ─────────────────────────────────────────────────────
output containerGroupId string = containerGroup.id
output containerGroupName string = containerGroup.name
output keyVaultName string = keyVault.name
output keyVaultUri string = keyVault.properties.vaultUri
output managedIdentityClientId string = managedIdentity.properties.clientId
output serverFqdn string = containerGroup.properties.ipAddress.fqdn
